Stack size reduction cleanup
darktable-org/rawspeed pull request #15
Opened 2017-01-05 14:25 UTC by axxel

As mentioned in my comment #163 on the former upstream repo from klauspost (https://github.com/klauspost/rawspeed/issues/163#issuecomment-259680348) regarding the solution to reduce the necessary stack size to support the musl libc, I think it is better to reduce the stack size of certain object instantiations inside the class than to force the user of the class to allocate the object on the heap.

Advantages:
 * more localized code changes
 * all usages of e.g. LJpegDecompressor profit at the same time
 * removed memory leaks that occur on exceptions

2017-01-05 14:51 UTC, LebedevRI reviewed
The diff looks good.
Will test and merge.

2017-01-05 17:27 UTC, LebedevRI requested changes
Uhm, @axxel, i'm seeing an awful lot of new AddressSanitizer overflows, e.g.:
```
./nikon corporation/nikon d800/RAW_NIKON_D800_14bit_FX_LOSSY.NEF
Loading file: "./nikon corporation/nikon d800/RAW_NIKON_D800_14bit_FX_LOSSY.NEF"
make: NIKON CORPORATION
model: NIKON D800
canonical_make: Nikon
canonical_model: D800
canonical_alias: D800
=================================================================
==21406==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x62d0001d4400 at pc 0x565118b36b15 bp 0x7ffcafe21640 sp 0x7ffcafe21638
WRITE of size 2 at 0x62d0001d4400 thread T0
    #0 0x565118b36b14 in RawSpeed::NikonDecompressor::DecompressNikon(RawSpeed::ByteStream*, unsigned int, unsigned int, unsigned int, unsigned int, unsigned int) /home/lebedevri/darktable/src/external/rawspeed/RawSpeed/NikonDecompressor.cpp:80
    #1 0x565118b316d1 in RawSpeed::NefDecoder::decodeRawInternal() /home/lebedevri/darktable/src/external/rawspeed/RawSpeed/NefDecoder.cpp:119
    #2 0x565118aa57f7 in RawSpeed::RawDecoder::decodeRaw() /home/lebedevri/darktable/src/external/rawspeed/RawSpeed/RawDecoder.cpp:687
    #3 0x565118a92da1 in main /home/lebedevri/darktable/src/external/rawspeed/RawSpeed/rawspeed-identify.cpp:169
    #4 0x7f1954e382b0 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x202b0)
    #5 0x565118a95ad9 in _start (/opt/darktable/bin/darktable-rs-identify+0x34ad9)

0x62d0001d4400 is located 0 bytes to the right of 32768-byte region [0x62d0001cc400,0x62d0001d4400)
allocated by thread T0 here:
    #0 0x7f1955fd2bf0 in operator new(unsigned long) (/usr/lib/x86_64-linux-gnu/libasan.so.3+0xc2bf0)
    #1 0x565118b358e3 in __gnu_cxx::new_allocator<unsigned short>::allocate(unsigned long, void const*) /usr/include/c++/6/ext/new_allocator.h:104
    #2 0x565118b358e3 in std::allocator_traits<std::allocator<unsigned short> >::allocate(std::allocator<unsigned short>&, unsigned long) /usr/include/c++/6/bits/alloc_traits.h:416
    #3 0x565118b358e3 in std::_Vector_base<unsigned short, std::allocator<unsigned short> >::_M_allocate(unsigned long) /usr/include/c++/6/bits/stl_vector.h:170
    #4 0x565118b358e3 in std::_Vector_base<unsigned short, std::allocator<unsigned short> >::_M_create_storage(unsigned long) /usr/include/c++/6/bits/stl_vector.h:185
    #5 0x565118b358e3 in std::_Vector_base<unsigned short, std::allocator<unsigned short> >::_Vector_base(unsigned long, std::allocator<unsigned short> const&) /usr/include/c++/6/bits/stl_vector.h:136
    #6 0x565118b358e3 in std::vector<unsigned short, std::allocator<unsigned short> >::vector(unsigned long, std::allocator<unsigned short> const&) /usr/include/c++/6/bits/stl_vector.h:280
    #7 0x565118b358e3 in RawSpeed::NikonDecompressor::DecompressNikon(RawSpeed::ByteStream*, unsigned int, unsigned int, unsigned int, unsigned int, unsigned int) /home/lebedevri/darktable/src/external/rawspeed/RawSpeed/NikonDecompressor.cpp:70
    #8 0x565118b316d1 in RawSpeed::NefDecoder::decodeRawInternal() /home/lebedevri/darktable/src/external/rawspeed/RawSpeed/NefDecoder.cpp:119
    #9 0x565118aa57f7 in RawSpeed::RawDecoder::decodeRaw() /home/lebedevri/darktable/src/external/rawspeed/RawSpeed/RawDecoder.cpp:687
    #10 0x565118a92da1 in main /home/lebedevri/darktable/src/external/rawspeed/RawSpeed/rawspeed-identify.cpp:169
    #11 0x7f1954e382b0 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x202b0)

SUMMARY: AddressSanitizer: heap-buffer-overflow /home/lebedevri/darktable/src/external/rawspeed/RawSpeed/NikonDecompressor.cpp:80 in RawSpeed::NikonDecompressor::DecompressNikon(RawSpeed::ByteStream*, unsigned int, unsigned int, unsigned int, unsigned int, unsigned int)
Shadow bytes around the buggy address:
  0x0c5a80032830: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c5a80032840: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c5a80032850: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c5a80032860: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c5a80032870: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
=>0x0c5a80032880:[fa]fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c5a80032890: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c5a800328a0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c5a800328b0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c5a800328c0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c5a800328d0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Heap right redzone:      fb
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack partial redzone:   f4
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==21406==ABORTING
```

Also, all rw2 raws report:
```
./panasonic/dmc-tz71/RAW_PANASONIC_DMC_TZ71_3-2.RW2
Loading file: "./panasonic/dmc-tz71/RAW_PANASONIC_DMC_TZ71_3-2.RW2"
make: Panasonic
model: DMC-TZ71
canonical_make: Panasonic
canonical_model: DMC-TZ71
canonical_alias: DMC-TZ71
=================================================================
==21728==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x629000009200 at pc 0x561bb75df3d9 bp 0x7f348e00ec70 sp 0x7f348e00ec68
READ of size 1 at 0x629000009200 thread T1
    #0 0x561bb75df3d8 in RawSpeed::PanaBitpump::getBits(int) /home/lebedevri/darktable/src/external/rawspeed/RawSpeed/Rw2Decoder.cpp:348
    #1 0x561bb75dfbf1 in RawSpeed::Rw2Decoder::decodeThreaded(RawSpeed::RawDecoderThread*) /home/lebedevri/darktable/src/external/rawspeed/RawSpeed/Rw2Decoder.cpp:149
    #2 0x561bb753bbe4 in RawSpeed::RawDecoderDecodeThread(void*) /home/lebedevri/darktable/src/external/rawspeed/RawSpeed/RawDecoder.cpp:623
    #3 0x7f349256f463 in start_thread (/lib/x86_64-linux-gnu/libpthread.so.0+0x7463)
    #4 0x7f3492c809de in __clone (/lib/x86_64-linux-gnu/libc.so.6+0xe89de)

0x629000009200 is located 0 bytes to the right of 16384-byte region [0x629000005200,0x629000009200)
allocated by thread T1 here:
    #0 0x7f3493d52d70 in operator new[](unsigned long) (/usr/lib/x86_64-linux-gnu/libasan.so.3+0xc2d70)
    #1 0x561bb75deeed in RawSpeed::PanaBitpump::PanaBitpump(RawSpeed::ByteStream*) /home/lebedevri/darktable/src/external/rawspeed/RawSpeed/Rw2Decoder.cpp:306
    #2 0x561bb75df8c2 in RawSpeed::Rw2Decoder::decodeThreaded(RawSpeed::RawDecoderThread*) /home/lebedevri/darktable/src/external/rawspeed/RawSpeed/Rw2Decoder.cpp:126
    #3 0x561bb753bbe4 in RawSpeed::RawDecoderDecodeThread(void*) /home/lebedevri/darktable/src/external/rawspeed/RawSpeed/RawDecoder.cpp:623
    #4 0x7f349256f463 in start_thread (/lib/x86_64-linux-gnu/libpthread.so.0+0x7463)

Thread T1 created by T0 here:
    #0 0x7f3493cc0f59 in __interceptor_pthread_create (/usr/lib/x86_64-linux-gnu/libasan.so.3+0x30f59)
    #1 0x561bb753e8eb in RawSpeed::RawDecoder::startThreads() /home/lebedevri/darktable/src/external/rawspeed/RawSpeed/RawDecoder.cpp:657
    #2 0x561bb75dda50 in RawSpeed::Rw2Decoder::DecodeRw2() /home/lebedevri/darktable/src/external/rawspeed/RawSpeed/Rw2Decoder.cpp:109
    #3 0x561bb75de078 in RawSpeed::Rw2Decoder::decodeRawInternal() /home/lebedevri/darktable/src/external/rawspeed/RawSpeed/Rw2Decoder.cpp:102
    #4 0x561bb753f7f7 in RawSpeed::RawDecoder::decodeRaw() /home/lebedevri/darktable/src/external/rawspeed/RawSpeed/RawDecoder.cpp:687
    #5 0x561bb752cda1 in main /home/lebedevri/darktable/src/external/rawspeed/RawSpeed/rawspeed-identify.cpp:169
    #6 0x7f3492bb82b0 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x202b0)

SUMMARY: AddressSanitizer: heap-buffer-overflow /home/lebedevri/darktable/src/extern [...]

2017-01-06 00:23 UTC, axxel commented
@LebedevRI Thanks a lot for the helpful feedback. I did in fact not check the changes with ASAN but will do so in the future. I added two commits fixing the Nikon and the Panasonic buffer overflow. Short explanation:
1. Nikon: This was a regression introduced by my reduction of the lookup table buffer size. See comments in my patch for details.
2. Panasonic: This was a bug that has been there before but was not detected by ASAN because it was a read overflow on the stack, not the heap. See comments in the patch for details.

2017-01-06 19:44 UTC, LebedevRI commented
Uhm, if i test this pr + #18, i get more leaks, e.g.
```
+ /home/lebedevri/rawspeed/build/RawSpeed/darktable-rs-identify './canon/canon powershot g15/RAW_CANON_POWERSHOT_G15.CR2'
WARNING: Couldn't find cameras.xml in '/usr/local/share/darktable/rawspeed/cameras.xml'
WARNING: Couldn't find cameras.xml in '/home/lebedevri/rawspeed/build/RawSpeed/../share/darktable/rawspeed/cameras.xml'
Loading file: "./canon/canon powershot g15/RAW_CANON_POWERSHOT_G15.CR2"
make: Canon
model: Canon PowerShot G15
canonical_make: Canon
canonical_model: PowerShot G15
canonical_alias: PowerShot G15
blackLevel: 128
whitePoint: 4095
blackLevelSeparate: -1 -1 -1 -1
wbCoeffs: 1833.000000 757.000000 1772.000000 nan
isCFA: 1
filters: 1229539657 (0x49494949)
bpp: 2
cpp: 1
dataType: 0
dimUncropped: 4160x3124
dimCropped: 4160x3124
cropOffset: 0x0
fuji_rotation_pos: 0
pixel_aspect_ratio: 1.000000
Image byte sum: 1692503954.000000
Image byte avg: 65.117143
Image uint16_t sum: 9646611344.000000
Image uint16_t avg: 742.284558

=================================================================
==9816==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 72 byte(s) in 1 object(s) allocated from:
    #0 0x7f3512c3cbf0 in operator new(unsigned long) (/usr/lib/x86_64-linux-gnu/libasan.so.3+0xc2bf0)
    #1 0x55dc6b9851c6 in RawSpeed::TiffIFD::TiffIFD(RawSpeed::FileMap*, unsigned int, unsigned int) /home/lebedevri/rawspeed/RawSpeed/TiffIFD.cpp:61
    #2 0x55dc6b9863a5 in RawSpeed::TiffIFD::parseMakerNote(RawSpeed::FileMap*, unsigned int, RawSpeed::Endianness) /home/lebedevri/rawspeed/RawSpeed/TiffIFD.cpp:272
    #3 0x55dc6b98543d in RawSpeed::TiffIFD::TiffIFD(RawSpeed::FileMap*, unsigned int, unsigned int) /home/lebedevri/rawspeed/RawSpeed/TiffIFD.cpp:84
    #4 0x55dc6b9863a5 in RawSpeed::TiffIFD::parseMakerNote(RawSpeed::FileMap*, unsigned int, RawSpeed::Endianness) /home/lebedevri/rawspeed/RawSpeed/TiffIFD.cpp:272
    #5 0x55dc6b98543d in RawSpeed::TiffIFD::TiffIFD(RawSpeed::FileMap*, unsigned int, unsigned int) /home/lebedevri/rawspeed/RawSpeed/TiffIFD.cpp:84
    #6 0x55dc6b9855ac in RawSpeed::TiffIFD::TiffIFD(RawSpeed::FileMap*, unsigned int, unsigned int) /home/lebedevri/rawspeed/RawSpeed/TiffIFD.cpp:101
    #7 0x55dc6b989c25 in RawSpeed::TiffParser::parseData() /home/lebedevri/rawspeed/RawSpeed/TiffParser.cpp:92
    #8 0x55dc6b97edb8 in RawSpeed::RawParser::getDecoder(RawSpeed::CameraMetaData*) /home/lebedevri/rawspeed/RawSpeed/RawParser.cpp:139
    #9 0x55dc6b95e257 in main /home/lebedevri/rawspeed/RawSpeed/rawspeed-identify.cpp:146
    #10 0x7f35118822b0 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x202b0)

SUMMARY: AddressSanitizer: 72 byte(s) leaked in 1 allocation(s).

```

Should i ignore leaks for now? `export ASAN_OPTIONS="detect_leaks=0"`

2017-01-06 22:12 UTC, axxel commented
I can't reproduce your latest _additional leak_ finding here. I started with my (latest) close-memory-leaks branch, merged it with my (rebased to current upstream) stack-size-reduction-cleanup branch and tested the mentioned file (found it in the old rawsamples.ch data set) with both rawspeed-identify as well as my test code -> no leaks.

2017-01-07 20:42 UTC, LebedevRI commented on RawSpeed/NikonDecompressor.cpp
> +  // 'curve' will hold a peace wise linearly interpolated function.
s/peace/piece/

2017-01-07 20:46 UTC, LebedevRI approved these changes
Ok, will merge.
No ASAN complaints, no new leaks, only one leak (https://github.com/darktable-org/rawspeed/pull/18#pullrequestreview-15611572), and according to `rstest`, no regressions.
Nice!

2017-01-07 20:47 UTC, merged

2017-01-07 20:47 UTC, LebedevRI commented
@axxel thank you!