DngDecoder should return blacklevels also for 2-component images.
darktable-org/rawspeed pull request #216
Opened 2020-01-11 16:57 UTC by jenshannoschwalm

These are observed in DNG's converted from dual pixels CR3 raws.
Wrong colors result from non-applying the blacklevels.

Second part to fix issue darktable-org#214

2020-01-11 18:18 UTC, LebedevRI commented
As i've noted in https://github.com/darktable-org/rawspeed/issues/215, i'm not confident that this is as simple as that,
that we aren't simply exchanging lack of blacklevel info with incorrect blacklevel info.

2020-01-11 18:36 UTC, jenshannoschwalm commented
What we miss is proper BlackLevel for both images. But when reading the 1.5 specs it says on page 26
"The values are stored in row-column-sample scan order." Doesn't this imply, that at least for the first image the read-in values are correct?

2020-01-11 19:35 UTC, LebedevRI requested changes
I'm not very sure that instead of not producing any info,
producing some likely known-broken info is good/better.

All that code so far clearly was designed for cpp=1,
i don't really buy that it is all magically correct for the cpp!=1 case.

In particular, `BLACKLEVEL` tag is defined in https://www.adobe.com/content/dam/acom/en/products/photoshop/pdfs/dng_spec_1.4.0.0.pdf as 
> Count BlackLevelRepeatRows * BlackLevelRepeatCols * SamplesPerPixel

Now SamplesPerPixel (cpp) is 2.
How are we accounting for that?
How //should// we be accounting for that?

2020-01-12 04:58 UTC, jenshannoschwalm commented
You cited just one part of the specs

> Count BlackLevelRepeatRows * BlackLevelRepeatCols * SamplesPerPixel

Refers to the count and here you are are right. We //should// in fact have not only 4 values but more as defined above. Right. We can **not** surely assume that blacklevel correction is the same for image2. Right again.

But the refs also says

> This tag specifies the zero light (a.k.a. thermal black or black current) encoding level, as a repeating pattern. The origin of this pattern is the top-left corner of the ActiveArea rectangle. The values are stored in row-column-sample scan order.

This means that black levels read-in as in current rawspeed code are absolutely correct for image1. So if i stay with image1 everything is fine. Of course there could be dual-raw where the blacklevels are different so for those image2 would not be correctly covered by this pr.

2020-02-22 19:10 UTC, jenshannoschwalm commented
@LebedevRI No chance to get this merged?

What is the problem? We have the number of blacklevel values defined by BlackLevelRepeatDim, this code is not touched. The (default) first 4 blacklevels are absolutely the same for cpp=1 or cpp=2 and are valid for the first sample.

See the 1.5 dng specs page 25 `The values are stored in row-column-sample scan order`

We would not get correct values for the second sample but we don't want to access that at all.

What would be required ...

2020-02-27 22:50 UTC, closed without merging

2020-02-27 22:56 UTC, LebedevRI commented
Now that there's a non-obscure working (affected) example (#225),
i think progress can be made here.
I think there may be some preparatory problems to handle before that:
1. The fact that we currently represent blacklevels as some abstract fixed-size 4-channel array is just broken.
2. Should we really store them as `float`s? Perhaps it should be rational.

2020-02-28 17:45 UTC, jenshannoschwalm commented
I confess i don't understand how this could help. Of course we have rationals that can't be expressed as a float or double but that can't be what you are hinting at.

BlackLevel is always SHORT, LONG or RATIONAL for dng.

Could you enlighten me?

2020-02-29 12:26 UTC, LebedevRI commented
I'm not saying it _would_ help, i'm just wondering if it would be more correct to not use `float` there.