Cr2Decoder cleanup (continuation)
darktable-org/rawspeed pull request #52
Opened 2017-01-26 23:20 UTC by axxel

Highlights:
 * remove/simplify lots of Cr2Decoder code and Canon quirk special handling
 * convert all required Canon related hints (related to quirks) to auto-detection
 * fixing #51 and #49

2017-01-27 07:07 UTC, LebedevRI commented on src/librawspeed/decompressors/LJpegDecompressor.cpp
> +  mRaw->metadata.subsampling.x = sof->compInfo[0].superH;
So #51 should be fixed?

2017-01-27 07:10 UTC, LebedevRI commented on src/librawspeed/decompressors/LJpegPlain.cpp
> +          dest += xStepSize;
And #49 too?

2017-01-27 08:51 UTC, LebedevRI commented
Bad news: git develop branch has an ASAN issue on canon 5dmk4 sRAW1 (mRAW, B13A0733.CR2).
Good news: it seems to be fixed in this pr...

2017-01-27 09:14 UTC, axxel commented on src/librawspeed/decompressors/LJpegDecompressor.cpp
> +  mRaw->metadata.subsampling.x = sof->compInfo[0].superH;
yes, see pr summary above

2017-01-27 09:14 UTC, axxel commented on src/librawspeed/decompressors/LJpegPlain.cpp
> +          dest += xStepSize;
yes, see pr summary above

2017-01-27 12:47 UTC, LebedevRI commented
Waiting for 80d samples.

2017-01-27 12:55 UTC, axxel commented
> Waiting for 80d samples.

Well, that may take 'forever', who knows. (I'm not going to buy an 80D just get this merged ;)). I got my samples from here: http://www.canonrumors.com/forum/index.php?topic=30139.msg604396#msg604396. So please use those as long as we don't have some on r.p.u.

2017-01-27 15:54 UTC, LebedevRI requested changes

2017-01-27 15:54 UTC, LebedevRI commented on data/cameras.xml
> -				<Hint name="wrapped_cr2_slices" value=""/>
then also remove `wrapped_cr2_slices` from xsd

2017-01-27 15:54 UTC, LebedevRI commented on data/cameras.xml
> -			<Hint name="old_format" value=""/>
then also remove `old_format`, `double_line_ljpeg` from xsd

2017-01-27 15:59 UTC, LebedevRI commented on src/librawspeed/tiff/TiffTag.h
> +  CANON_RAW_DATA_OFFSET           = 0x0081, // MakerNote TIF
nice :)

2017-01-27 16:13 UTC, axxel commented on data/cameras.xml
> -			<Hint name="old_format" value=""/>
right. also missed one remainging old_format hint in the xml. thanks.

2017-01-27 16:14 UTC, LebedevRI commented
And one 'forever' later :)

2017-01-27 16:21 UTC, axxel commented
> And one 'forever' later :)

Nice! :D The filenames are different, so I guess it was someone else uploading those. The guy I contacted has not answered my e-mail.

2017-01-27 16:23 UTC, dabbill commented
@axxel I was the one that got basic 80D support added to DT. 
@LebedevRI NP, always try to help when I can.

2017-01-27 18:31 UTC, merged

2017-01-27 19:27 UTC, LebedevRI commented
@axxel speaking of 80d, there is this one(?) raw that is still broken even with this code.
I'm not sure what's going on https://redmine.darktable.org/issues/11367

2017-01-28 12:39 UTC, axxel commented
Interesting. I'll have a look but my current guess is, the file is simply broken. The bug discussion seems not to say anything about the same file working in other software, right?

2017-01-28 12:41 UTC, LebedevRI commented
> The bug discussion seems not to say anything about the same file working in other software, right?

As far as i can tell, yes. Perhaps it was simply modified by some tool, which explicitly makes such bug wontfix.

2017-01-30 12:35 UTC, axxel commented
> Perhaps it was simply modified by some tool, which explicitly makes such bug wontfix.

I tried processing it with dcraw, same result. dcraw even reports: `Corrupt data near 0x8d4001`.

2017-01-30 12:35 UTC, LebedevRI commented
Cool, wontfix them