Remove "no-samples" for Fujifilm FinePix S9600fd
darktable-org/rawspeed pull request #731
Opened 2024-06-13 14:42 UTC by victoryforce

S9600fd is just S9600 with face detection (and for S9600 we have a sample in RPU). In the Fujifilm model line, there were several cases of models being released without and with the `fd` suffix. Such models are identical in everything else except for the presence of face detection code in the camera firmware.

So we can avoid annoying the user with "no-samples" warnings for S9600fd.

2024-06-13 15:00 UTC, LebedevRI requested changes
First, if that is a standalone camera entry, it must have samples.

Second, clearly we aren't bothering them enough since there's still no RPU sample for S9600fd in review queue. /s

Thirdly, if this is the exact same camera, it's whole `<Camera>` should be 
```
		<Aliases>
			<Alias id="FinePix S9600fd">Fujifilm FinePix S9600fd</Alias>
		</Aliases>
```
in `<Camera>` for `S9600`. I think that will also silence that begging too.

2024-06-13 17:54 UTC, victoryforce commented
> First, if that is a standalone camera entry, it must have samples.
> 
> Second, clearly we aren't bothering them enough since there's still no RPU sample for S9600fd in review queue. /s

This camera is almost two decades old, so we shouldn't expect many darktable users to process images from this camera. And this makes it very unlikely that we will ever see samples from this particular camera model. :(


> Thirdly, if this is the exact same camera, it's whole `<Camera>` should be
> 
> ```
> 		<Aliases>
> 			<Alias id="FinePix S9600fd">Fujifilm FinePix S9600fd</Alias>
> 		</Aliases>
> ```
> 
> in `<Camera>` for `S9600`. I think that will also silence that begging too.

I agree. The xml entries for these two cameras are identical, so the replacement to Alias was a natural choice. I simply chose the fix that made the least change to the current data. Changed.

2024-06-13 18:03 UTC, merged

2024-06-13 18:03 UTC, LebedevRI commented
@victoryforce thank you!

2024-06-14 06:55 UTC, kmilos commented on data/cameras.xml
> +			<Alias id="FinePix S9600fd">Fujifilm FinePix S9600fd</Alias>
This is wrong and won't work - should just say `<Alias>FinePix S9600fd</Alias>` (i.e., [the actual value and the `id` attribute should be identical in this case, so the attribute can be omitted](https://github.com/darktable-org/rawspeed/tree/develop/data#camera-model-aliases)).

Please fix before merging to stable and uploading to dt submodule. @victoryforce @LebedevRI

2024-06-14 09:44 UTC, victoryforce commented on data/cameras.xml
> +			<Alias id="FinePix S9600fd">Fujifilm FinePix S9600fd</Alias>
Oh, drat! I just copy-pasted the suggested string, although I could have noticed that a little higher in the file there is Alias ​​written differently... :( Thanks for noticing!

2024-06-14 16:19 UTC, LebedevRI commented on data/cameras.xml
> +			<Alias id="FinePix S9600fd">Fujifilm FinePix S9600fd</Alias>
Yeah, as i've said previously, i don't fully understand/remember this `<Alias>` syntax.
I thought that is what the right line is, based on what happens for Canon entries.
@kmilos thanks!