Complete the TiffIFD/TiffEntry interface cleanup
darktable-org/rawspeed pull request #75
Opened 2017-02-05 15:39 UTC by axxel

* make getter function names consistent
* complete const-correctness of TiffIFD interface

2017-02-05 15:41 UTC, LebedevRI commented on src/librawspeed/decoders/AbstractTiffDecoder.cpp
> +    ThrowRDE("AbstractTiffDecoder: No suitable IFD with IMAGEWIDTH tag found.");
with `filter` you mean

2017-02-05 15:45 UTC, axxel commented on src/librawspeed/decoders/AbstractTiffDecoder.cpp
> +    ThrowRDE("AbstractTiffDecoder: No suitable IFD with IMAGEWIDTH tag found.");
absolutely right. see update.

2017-02-09 09:18 UTC, axxel commented
@LebedevRI Please merge (as early as convenient :)).

2017-02-09 17:36 UTC, LebedevRI commented on src/librawspeed/decoders/MosDecoder.cpp
> +  } catch(...) {
using exceptions for normal codepath handlign, wtf c++?

2017-02-09 17:38 UTC, LebedevRI commented on src/librawspeed/decoders/Rw2Decoder.cpp
> +    raw = mRootIFD->getIFDWithTag(PANASONIC_STRIPOFFSET);
i really don't like this pattern

2017-02-09 17:45 UTC, LebedevRI requested changes
i *really* don't like that pattern of using exception handling as general-purpose codeflow mechaninsm that you are adding e.g. in `MosDecoder.cpp`.

2017-02-09 21:43 UTC, axxel commented
Well, there is _tons_ of 'prior art' in the code base for using exceptions to deal with 'non fatal' error conditions and it is not time critical either. So I don't see any reason why this would be an issue. But I see even less of a point in starting an argument over this detail. See appended patch.

2017-02-09 23:02 UTC, axxel commented
@LebedevRI you probably noticed, but just in case you did not and are waiting for this to be fixed: the compile issue seems to be caused by your recent gtest-option commit or something else build system related.

2017-02-10 09:13 UTC, LebedevRI commented
@axxel if the build breaks, i have all kinds of bells and whistles that start start signalling, so i do notice :)
Fixed now, please push something :)

2017-02-10 10:13 UTC, axxel commented
> so i do notice :)

:). Your usual approach to have a 'next' pr to get ci-feedback before merging seemed like a valid strategy to prevent breaking the 'default' build.

2017-02-10 10:24 UTC, LebedevRI commented
Just re-triggering the build does not seem to help, so please rebase.

2017-02-10 12:11 UTC, LebedevRI commented
> Well, there is tons of 'prior art' in the code base for using exceptions to deal with 'non fatal' error conditions and it is not time critical either. So I don't see any reason why this would be an issue. 

Since you want to touch everything immediately, you leave me no other option on how to change 'prior art' but to complain about it when i see it in the diff

2017-02-10 12:13 UTC, LebedevRI commented on src/librawspeed/decoders/Rw2Decoder.cpp
> +    raw = mRootIFD->getIFDWithTag(PANASONIC_STRIPOFFSET);
this is still here

2017-02-10 12:14 UTC, LebedevRI commented on src/librawspeed/decoders/Rw2Decoder.cpp
> +    raw = mRootIFD->getIFDWithTag(PANASONIC_STRIPOFFSET);
this is still here

2017-02-10 12:22 UTC, axxel commented on src/librawspeed/decoders/Rw2Decoder.cpp
> +    raw = mRootIFD->getIFDWithTag(PANASONIC_STRIPOFFSET);
indeed

2017-02-10 15:05 UTC, LebedevRI approved these changes
Okay, seems to work :)
Will merge.

2017-02-10 15:06 UTC, merged

2017-02-10 15:06 UTC, LebedevRI commented
@axxel thank you.